### PR TITLE
Add Tea::AWSRegion

### PR DESCRIPTION
**Pull request by alexjurkiewicz**

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @alexjurkiewicz, can you please rebase after https://github.com/voxpupuli/puppet-tea/pull/15 is merged?

**Comment by bastelfreak** [comment]
aaand its merged

**Comment by alexjurkiewicz** [comment]
Done, you may want to squash on merge

**Comment by bastelfreak** [comment]
Thanks!

**Pull request merged**
