### PR TITLE
Readability and usability improvements

### PR DESCRIPTION
**Pull request by ahpook**
Tweaked the readme slightly. I made some sample classes to exercise the types too.

Don't know if you want this in the repo or wanted to just keep it purely types - just figured i'd push it up.

### CODE REVIEW

**Comment by igalic** [comment]
I am confused about the manifests/ stuff…
i'd move it into examples/

**Comment by bastelfreak** [comment]
Hi @ahpook, should the pp files move to examples/?

**Comment by ahpook** [comment]
@bastelfreak @igalic OK done! Sorry 'bout my slowness...

**Comment by bastelfreak** [comment]
thanks \o/

**Comment by ahpook** [comment]
🎉

**Pull request merged**
